import asyncio
import hashlib
import logging
import os
import re
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timedelta

from dotenv import load_dotenv
import easyocr
import cv2
import numpy as np
from supabase import create_client, Client

load_dotenv()
from telegram import (
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    Update,
)
from telegram.request import HTTPXRequest
from telegram.ext import (
    Application,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

BOT_TOKEN = os.environ.get("BOT_TOKEN")
TARGET_CHANNEL = os.environ.get("TARGET_CHANNEL", "optoviygr")
CARD_NUMBER = os.environ.get("CARD_NUMBER", "4255190154088028")
PAYMENT_AMOUNT = os.environ.get("PAYMENT_AMOUNT", "5")
POST_LIFETIME_HOURS = int(os.environ.get("POST_LIFETIME_HOURS", "24"))
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_ANON_KEY = os.environ.get("SUPABASE_ANON_KEY")

_ocr_reader = easyocr.Reader(["en", "ru"], verbose=False)

_supabase: Client | None = None


class State:
    START = "start"
    AWAITING_PROOF = "awaiting_proof"
    AWAITING_POST = "awaiting_post"


@dataclass
class UserState:
    state: str = State.START
    payment_confirmed: bool = False
    post_message_id: int | None = None
    payment_verified_at: datetime | None = None
    bot_message_ids: list[int] = field(default_factory=list)


_user_states: dict[int, UserState] = {}


def get_user_state(user_id: int) -> UserState:
    if user_id not in _user_states:
        _user_states[user_id] = UserState()
    return _user_states[user_id]


def reset_user_state(user_id: int):
    _user_states.pop(user_id, None)


def _get_supabase() -> Client | None:
    """Return the Supabase client (lazily initialized) or None."""
    global _supabase
    if _supabase is None and SUPABASE_URL and SUPABASE_ANON_KEY:
        _supabase = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
    return _supabase


CREATE_TABLE_SQL = """
create table if not exists public.screenshots (
    id            bigint generated by default as identity primary key,
    file_hash     text,
    image_hash    text unique,
    text_hash     text unique,
    check_number  text unique,
    file_unique_id text unique,
    user_id       bigint not null,
    created_at    timestamptz default now()
);
create index if not exists idx_screenshots_hashes
    on public.screenshots (file_hash, image_hash, text_hash, check_number);
""".strip()


def _init_db():
    """Initialize the Supabase client and verify the screenshots table.

    The ``screenshots`` table must be pre-created in the Supabase SQL
    editor.  See ``CREATE_TABLE_SQL`` above.
    """
    supabase = _get_supabase()
    if supabase is None:
        logger.warning(
            "SUPABASE_URL / SUPABASE_ANON_KEY not set — "
            "duplicate detection is DISABLED. Duplicate payments will PASS!"
        )
        return False

    try:
        supabase.table("screenshots").select("id").limit(0).execute()
        logger.info("Supabase table 'screenshots' verified — duplicate detection active")
        return True
    except Exception as e:
        logger.error(
            "Supabase table 'screenshots' not found or inaccessible. "
            "Duplicate detection DISABLED.\n"
            "RUN THIS SQL in Supabase SQL Editor:\n%s", e, CREATE_TABLE_SQL
        )
        return False


def _compute_file_hash(file_path: str) -> str:
    """Return the SHA-256 hex digest of the file at *file_path*."""
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _compute_image_hash(file_path: str) -> str:
    """Compute a perceptual hash (pHash via DCT) of the image.

    Falls back to a plain file hash when OpenCV cannot read the image.
    """
    img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return _compute_file_hash(file_path)

    img_resized = cv2.resize(img, (32, 32))
    dct = cv2.dct(np.float32(img_resized))
    dct_low = dct[:8, :8]
    avg = dct_low.mean()
    diff = dct_low > avg
    return "".join(str(int(b)) for b in diff.flatten())


def _screenshot_exists(file_hash: str, image_hash: str) -> bool:
    """Return True if a screenshot with either hash is already stored."""
    supabase = _get_supabase()
    if supabase is None:
        return False
    try:
        resp = supabase.table("screenshots").select("id").or_(
            f"file_hash.eq.{file_hash},image_hash.eq.{image_hash}"
        ).limit(1).execute()
        return len(resp.data) > 0
    except Exception:
        logger.exception("Supabase _screenshot_exists query failed")
        return False


def _file_unique_id_exists(file_unique_id: str) -> bool:
    """Return True if this Telegram file_unique_id was already used.

    Telegram guarantees a stable ``file_unique_id`` for identical file
    content even across different users.
    """
    supabase = _get_supabase()
    if supabase is None:
        return False
    try:
        resp = (
            supabase.table("screenshots")
            .select("id")
            .eq("file_unique_id", file_unique_id)
            .limit(1)
            .execute()
        )
        return len(resp.data) > 0
    except Exception:
        logger.exception("Supabase _file_unique_id_exists query failed")
        return False


def _normalize_text(text: str) -> str:
    """Normalize OCR text for deduplication.

    Lowercases, removes whitespace, strips non-alphanumeric characters,
    and removes date/time patterns so that screenshots of the same
    payment taken at different times still produce the same hash.
    """
    text = text.lower()
    # Remove time patterns with colon: HH:MM, HH:MM:SS
    text = re.sub(r"\d{1,2}:\d{2}(:\d{2})?", "", text)
    # Remove dates with separator chars: DD.MM.YYYY, DD/MM/YYYY, YYYY-MM-DD
    text = re.sub(r"\d{1,2}[\./\-]\d{1,2}[\./\-]\d{2,4}", "", text)
    text = re.sub(r"\d{2,4}[\./\-]\d{2}[\./\-]\d{2,4}", "", text)
    text = re.sub(r"\s+", "", text)
    text = re.sub(r"[^a-z0-9]", "", text)
    return text


def _compute_text_hash(text: str) -> str:
    """Return a SHA-256 hash of the normalized OCR text."""
    normalized = _normalize_text(text)
    return hashlib.sha256(normalized.encode()).hexdigest()


def _text_hash_exists(text_hash: str) -> bool:
    """Return True if this OCR text hash is already stored."""
    supabase = _get_supabase()
    if supabase is None:
        return False
    try:
        resp = (
            supabase.table("screenshots")
            .select("id")
            .eq("text_hash", text_hash)
            .limit(1)
            .execute()
        )
        return len(resp.data) > 0
    except Exception:
        logger.exception("Supabase _text_hash_exists query failed")
        return False


def _check_number_exists(check_number: str) -> bool:
    """Return True if this check/reference number was already used."""
    supabase = _get_supabase()
    if supabase is None:
        return False
    try:
        resp = (
            supabase.table("screenshots")
            .select("id")
            .eq("check_number", check_number)
            .limit(1)
            .execute()
        )
        return len(resp.data) > 0
    except Exception:
        logger.exception("Supabase _check_number_exists query failed")
        return False


def _extract_check_number(text: str) -> str | None:
    """Extract the payment check/reference number from OCR text.

    Looks for common labels that precede a check number and returns
    the token that follows. Returns *None* when nothing is found.
    The *text* argument should already be lowercased.
    """
    patterns = [
        r"номер\s*чека[:\s№]*([a-z0-9\-]{4,})",
        r"чек[:\s№]*([a-z0-9\-]{4,})",
        r"номер\s*оплаты[:\s]*([a-z0-9\-]{4,})",
        r"номер\s*транзакции[:\s]*([a-z0-9\-]{4,})",
        r"номер\s*платежа[:\s]*([a-z0-9\-]{4,})",
        r"номер\s*операции[:\s]*([a-z0-9\-]{4,})",
        r"идентификатор\s*плат[её]жа[:\s]*([a-z0-9\-]{4,})",
        r"идентификатор\s*транзакции[:\s]*([a-z0-9\-]{4,})",
        r"реквизиты[:\s]*([a-z0-9\-]{6,})",
        r"реф[:\s]*([a-z0-9\-]{4,})",
        r"референс[:\s]*([a-z0-9\-]{4,})",
        r"ref[:\s]*([a-z0-9]{4,})",
        r"transaction\s*id[:\s]*([a-z0-9\-]{4,})",
        r"оплата[:\s№]*([0-9]{4,})",
        r"номер[:\sу]*([0-9]{6,})",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        if match:
            return match.group(1).strip()
    return None


def _store_screenshot(file_hash: str, image_hash: str, text_hash: str,
                      check_number: str | None, user_id: int, file_unique_id: str):
    """Persist a verified screenshot so it can't be reused."""
    supabase = _get_supabase()
    if supabase is None:
        return
    try:
        supabase.table("screenshots").insert({
            "file_hash": file_hash,
            "image_hash": image_hash,
            "text_hash": text_hash,
            "check_number": check_number,
            "file_unique_id": file_unique_id,
            "user_id": user_id,
            "created_at": datetime.now().isoformat(),
        }).execute()
    except Exception as e:
        # Ignore unique-constraint violations — they mean a race condition
        # caused the same file to be stored twice (the pre-checks should
        # prevent this, but concurrent requests can slip through).
        err_str = str(e)
        if "23505" in err_str or "duplicate" in err_str.lower():
            logger.debug("Ignoring duplicate insert (race condition)")
        else:
            logger.exception("Supabase _store_screenshot insert failed")


WELCOME_TEXT = (
    "Привет! Я - автоматический бот, который поможет тебе "
    "опубликовать свой пост в канале @{channel}\n\n"
    "Стоимость 1 публикации - {amount} белорусских рублей. "
    "Публикация будет размещена в канале {hours} часа, "
    "а затем удаляется.\n\n"
    "Если хочешь оплатить публикацию, то нажми кнопку"
).format(channel=TARGET_CHANNEL, amount=PAYMENT_AMOUNT, hours=POST_LIFETIME_HOURS)

PAYMENT_TEXT = (
    "Отлично! Переведи {amount} белорусских рублей на карту:\n\n"
    "<b>{card}</b>\n\n"
    "После оплаты нажми кнопку «Я оплатил» и пришли "
    "скриншот подтверждения."
).format(amount=PAYMENT_AMOUNT, card=CARD_NUMBER)

PROOF_REQUEST_TEXT = (
    "Пришли снимок экрана (скриншот) подтверждения оплаты "
    "переводом на карту {card} в размере {amount} белорусских рублей."
).format(card=CARD_NUMBER, amount=PAYMENT_AMOUNT)

VERIFICATION_TEXT = "Проверяю оплату..."

VERIFICATION_SUCCESS = (
    "Оплата подтверждена! ✅\n\n"
    "Теперь можешь отправить пост, который хочешь "
    "увидеть в канале @{channel}.\n"
    "Можно прислать фотографию с подписью или просто текст — "
    "каждый вариант опубликуется в канале."
).format(channel=TARGET_CHANNEL)

VERIFICATION_FAIL = (
    "Не удалось автоматически подтвердить оплату.\n\n"
    "Проверь, что на скриншоте видна:\n"
    "- сумма {amount} BYN\n"
    "- карта {card}\n"
    "- текущие дата и время\n\n"
    "Попробуй отправить более четкий скриншот."
).format(amount=PAYMENT_AMOUNT, card=CARD_NUMBER)

DUPLICATE_SCREENSHOT_TEXT = "Запрос отклонён"

DUPLICATE_CHECK_NUMBER_TEXT = "Запрос отклонён"

POST_RECEIVED_TEXT = (
    "Пост получен! Он опубликован в канале @{channel}."
).format(channel=TARGET_CHANNEL)

START_BUTTONS = InlineKeyboardMarkup(
    [[InlineKeyboardButton("Продолжить", callback_data="continue")]]
)

PAYMENT_BUTTONS = InlineKeyboardMarkup(
    [[InlineKeyboardButton("Я оплатил", callback_data="paid")]]
)

PROOF_SENT_BUTTONS = InlineKeyboardMarkup(
    [
        [InlineKeyboardButton("Отправить скриншот снова", callback_data="resend_proof")],
    ]
)


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    reset_user_state(user_id)
    state = get_user_state(user_id)
    state.state = State.START

    welcome = await update.message.reply_text(WELCOME_TEXT, reply_markup=START_BUTTONS)
    state.bot_message_ids.append(welcome.message_id)


async def button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    user_id = update.effective_user.id
    state = get_user_state(user_id)

    if query.data == "continue":
        state.state = State.AWAITING_PROOF
        await query.edit_message_text(
            PAYMENT_TEXT, reply_markup=PAYMENT_BUTTONS, parse_mode="HTML"
        )

    elif query.data == "paid":
        state.state = State.AWAITING_PROOF
        await query.edit_message_text(
            PROOF_REQUEST_TEXT, reply_markup=PROOF_SENT_BUTTONS
        )

    elif query.data == "resend_proof":
        state.state = State.AWAITING_PROOF
        await query.edit_message_text(
            PROOF_REQUEST_TEXT, reply_markup=PROOF_SENT_BUTTONS
        )


async def handle_photo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    state = get_user_state(user_id)

    if state.state == State.AWAITING_POST:
        photo = update.message.photo[-1]
        caption = update.message.caption or ""

        try:
            sent = await context.bot.send_photo(
                chat_id=f"@{TARGET_CHANNEL}",
                photo=photo.file_id,
                caption=caption,
            )
            state.post_message_id = sent.message_id

            await _cleanup_chat_messages(context, user_id, state.bot_message_ids)

            final = await context.bot.send_message(chat_id=user_id, text=POST_RECEIVED_TEXT)
            state.bot_message_ids = [final.message_id]

            _schedule_deletion(context, sent.message_id)
            reset_user_state(user_id)
        except Exception:
            logger.exception("Failed to publish post")
            await update.message.reply_text(
                "Ошибка при публикации поста. Убедись, что бот "
                "добавлен в канал @{channel} с правом публиковать.".format(
                    channel=TARGET_CHANNEL
                )
            )
        return

    if state.state != State.AWAITING_PROOF:
        msg = await update.message.reply_text("Нажми кнопку «Продолжить» чтобы начать.")
        state.bot_message_ids.append(msg.message_id)
        return

    verif_msg = await update.message.reply_text(VERIFICATION_TEXT)
    state.bot_message_ids.append(verif_msg.message_id)

    photo = update.message.photo[-1]
    file = await context.bot.get_file(photo.file_id)

    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        await file.download_to_drive(custom_path=tmp.name)
        tmp_path = tmp.name

    file_hash = _compute_file_hash(tmp_path)
    image_hash = _compute_image_hash(tmp_path)

    # Check 1: file hash + perceptual hash (exact and visual duplicates)
    if _screenshot_exists(file_hash, image_hash):
        os.unlink(tmp_path)
        logger.info("Duplicate detected via file/image hash for user %s", user_id)
        fail_msg = await update.message.reply_text(
            DUPLICATE_SCREENSHOT_TEXT, reply_markup=PROOF_SENT_BUTTONS
        )
        state.bot_message_ids.append(fail_msg.message_id)
        return

    # Check 2: Telegram file_unique_id (same file content → same ID)
    if photo.file_unique_id and _file_unique_id_exists(photo.file_unique_id):
        os.unlink(tmp_path)
        logger.info("Duplicate detected via file_unique_id for user %s", user_id)
        fail_msg = await update.message.reply_text(
            DUPLICATE_SCREENSHOT_TEXT, reply_markup=PROOF_SENT_BUTTONS
        )
        state.bot_message_ids.append(fail_msg.message_id)
        return

    verified = False
    check_number = None
    ocr_text = ""
    try:
        verified, check_number, ocr_text = await verify_payment_screenshot(tmp_path)
    except Exception:
        logger.exception("OCR verification error")
        verified = False
    finally:
        os.unlink(tmp_path)

    if verified:
        # Check 3: normalized OCR text hash (catches re-encoded images
        # with different bytes but same content words)
        text_hash = _compute_text_hash(ocr_text)
        if _text_hash_exists(text_hash):
            logger.info("Duplicate detected via text_hash for user %s", user_id)
            fail_msg = await update.message.reply_text(
                DUPLICATE_SCREENSHOT_TEXT, reply_markup=PROOF_SENT_BUTTONS
            )
            state.bot_message_ids.append(fail_msg.message_id)
            return

        # Check 4: payment check/reference number
        if check_number and _check_number_exists(check_number):
            logger.info("Duplicate detected via check_number=%s for user %s",
                        check_number, user_id)
            fail_msg = await update.message.reply_text(
                DUPLICATE_CHECK_NUMBER_TEXT, reply_markup=PROOF_SENT_BUTTONS
            )
            state.bot_message_ids.append(fail_msg.message_id)
            return

        _store_screenshot(file_hash, image_hash, text_hash, check_number,
                          user_id, photo.file_unique_id)
        logger.info(
            "Payment verified for user %s — stored. "
            "check_number=%s, has_text_hash=%s",
            user_id, check_number, bool(text_hash),
        )
        state.payment_confirmed = True
        state.state = State.AWAITING_POST
        state.payment_verified_at = datetime.now()
        success_msg = await update.message.reply_text(VERIFICATION_SUCCESS)
        state.bot_message_ids.append(success_msg.message_id)
    else:
        fail_msg = await update.message.reply_text(VERIFICATION_FAIL, reply_markup=PROOF_SENT_BUTTONS)
        state.bot_message_ids.append(fail_msg.message_id)


async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    state = get_user_state(user_id)

    if state.state == State.AWAITING_POST:
        text = update.message.text

        try:
            sent = await context.bot.send_message(
                chat_id=f"@{TARGET_CHANNEL}",
                text=text,
            )
            state.post_message_id = sent.message_id

            await _cleanup_chat_messages(context, user_id, state.bot_message_ids)

            final = await context.bot.send_message(chat_id=user_id, text=POST_RECEIVED_TEXT)
            state.bot_message_ids = [final.message_id]

            _schedule_deletion(context, sent.message_id)
            reset_user_state(user_id)
        except Exception:
            logger.exception("Failed to publish text post")
            await update.message.reply_text(
                "Ошибка при публикации поста. Убедись, что бот "
                "добавлен в канал @{channel} с правом публиковать.".format(
                    channel=TARGET_CHANNEL
                )
            )

    elif state.state == State.AWAITING_PROOF:
        msg = await update.message.reply_text(
            "Пожалуйста, пришли снимок экрана (скриншот) подтверждения оплаты."
        )
        state.bot_message_ids.append(msg.message_id)

    else:
        msg = await update.message.reply_text(
            "Нажми кнопку «Продолжить» чтобы начать."
        )
        state.bot_message_ids.append(msg.message_id)


async def _delete_post(context: ContextTypes.DEFAULT_TYPE):
    data = context.job.data
    try:
        await context.bot.delete_message(chat_id=data["chat_id"], message_id=data["message_id"])
    except Exception:
        pass


def _schedule_deletion(context: ContextTypes.DEFAULT_TYPE, message_id: int):
    """Schedule auto-deletion of a channel post after POST_LIFETIME_HOURS.

    Wrapped in its own try/except so that job-scheduling failures don't
    cause the post-publish flow to report an error to the user.
    """
    if POST_LIFETIME_HOURS <= 0:
        return
    try:
        if context.job_queue is None:
            logger.warning("JobQueue not available — skipping auto-deletion scheduling")
            return
        context.job_queue.run_once(
            _delete_post,
            when=POST_LIFETIME_HOURS * 3600,
            data={"chat_id": f"@{TARGET_CHANNEL}", "message_id": message_id},
            name=f"delete_post_{message_id}",
        )
    except Exception:
        logger.exception("Failed to schedule post deletion – post remains live")


async def _cleanup_chat_messages(context: ContextTypes.DEFAULT_TYPE, user_id: int, message_ids: list[int]):
    """Delete all bot messages in the private chat up to the start message."""
    for msg_id in message_ids:
        try:
            await context.bot.delete_message(chat_id=user_id, message_id=msg_id)
        except Exception:
            logger.debug("Could not delete message %s in chat %s", msg_id, user_id)


def _check_datetime_in_text(text: str) -> bool:
    """Check if the OCR text contains a date/time matching the current time.

    Accepts a screenshot only if it shows today's date (in any common
    format) or a time within ±10 minutes of now.
    """
    now = datetime.now()
    text_compact = re.sub(r"\s+", "", text)
    text_lower = text.lower()

    date_formats = [
        now.strftime("%d%m%Y"),
        now.strftime("%y%m%Y"),
        now.strftime("%Y%m%d"),
        now.strftime("%d%m%y"),
        now.strftime("%d.%m.%Y"),
        now.strftime("%d.%m.%y"),
        now.strftime("%d/%m/%Y"),
        now.strftime("%d-%m-%Y"),
        now.strftime("%Y-%m-%d"),
    ]

    for ds in date_formats:
        if ds in text_compact or ds.lower() in text_lower:
            return True

    for delta in range(-10, 11):
        check_time = now + timedelta(minutes=delta)
        time_str = check_time.strftime("%H:%M")
        time_compact = check_time.strftime("%H%M")
        if time_str in text or time_compact in text_compact:
            return True

    return False


async def verify_payment_screenshot(image_path: str) -> tuple[bool, str | None, str]:
    """Automatically verify a payment screenshot using OCR.

    Returns a tuple of ``(verification_passed, check_number_or_None, ocr_text)``
    where *check_number* is the payment reference extracted from the OCR
    text and *ocr_text* is the raw normalized OCR text used for duplicate
    detection.
    """
    if _ocr_reader is None:
        return False, None, ""

    try:
        results = _ocr_reader.readtext(image_path, detail=0)
        text = " ".join(results).lower()
    except Exception:
        return False, None, ""

    logger.info("OCR recognized text: %s", text)

    card_str = CARD_NUMBER.replace(" ", "").replace("-", "")
    text_compact = text.replace(" ", "").replace("-", "").replace("*", "")
    card_in_text = card_str in text_compact

    card_prefix = card_str[:4]
    card_suffix = card_str[-4:]
    card_prefix_found = card_prefix in text_compact
    card_suffix_found = card_suffix in text_compact

    # Require BOTH prefix and suffix — a different card won't match both
    card_any = card_in_text or (card_prefix_found and card_suffix_found)

    masked_card = re.search(
        rf"{card_prefix}[\dx*абвгдеёжзийклмнопрстуфхцчшщъыьэюяa-z\*\•]{{6,}}{card_suffix}",
        text_compact,
    ) is not None

    amount_patterns = [
        rf"{PAYMENT_AMOUNT}\.0+\s*byn",
        rf"{PAYMENT_AMOUNT},0+\s*byn",
        rf"{PAYMENT_AMOUNT}\s*byn",
        rf"{PAYMENT_AMOUNT}\.0+\s*brl",
        rf"{PAYMENT_AMOUNT}\s*brl",
        rf"{PAYMENT_AMOUNT}\.0+\s*бел?о?р?у?с?с?к?и?х?\s*руб",
        rf"{PAYMENT_AMOUNT}\.0+\s*руб",
        rf"{PAYMENT_AMOUNT}\s*бел?о?р?у?с?с?к?и?х?\s*руб",
        rf"{PAYMENT_AMOUNT}\s*руб",
    ]

    amount_found = any(
        re.search(pattern, text, re.IGNORECASE | re.DOTALL) for pattern in amount_patterns
    )

    if not amount_found:
        amount_found = bool(
            re.search(rf"{PAYMENT_AMOUNT}\.\d{{1,2}}\s*(byn|brl|руб|бел)", text, re.IGNORECASE)
            or re.search(rf"{PAYMENT_AMOUNT},\d{{1,2}}\s*(byn|brl|руб|бел)", text, re.IGNORECASE)
        )

    payment_keywords = [
        "успешно",
        "проведена",
        "завершена",
        "карта получателя",
        "сумма перевода",
        "номер чека",
        "банк",
    ]
    keywords_found = any(kw in text for kw in payment_keywords)

    datetime_found = _check_datetime_in_text(text)

    logger.info(
        "Verification: amount_found=%s, card_any=%s, keywords=%s, masked_card=%s, datetime_found=%s",
        amount_found, card_any, keywords_found, masked_card, datetime_found,
    )

    verified = (
        amount_found and card_any
        and (keywords_found or masked_card)
        and datetime_found
    )

    check_number = _extract_check_number(text) if verified else None
    return verified, check_number, text


async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE):
    logger.error("Exception while handling update:", exc_info=context.error)


def main():
    if not BOT_TOKEN:
        logger.error("BOT_TOKEN environment variable is not set!")
        raise SystemExit(1)

    request = HTTPXRequest(
        read_timeout=60,
        connect_timeout=30,
        write_timeout=60,
    )
    application = Application.builder().token(BOT_TOKEN).request(request).build()

    db_ok = _init_db()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CallbackQueryHandler(button_handler))
    application.add_handler(
        MessageHandler(filters.PHOTO & filters.ChatType.PRIVATE, handle_photo)
    )
    application.add_handler(
        MessageHandler(
            filters.TEXT & ~filters.COMMAND & filters.ChatType.PRIVATE, handle_text
        )
    )
    application.add_error_handler(error_handler)

    logger.info("Bot started. Target channel: @%s", TARGET_CHANNEL)
    logger.info("Card: %s, Amount: %s BYN", CARD_NUMBER, PAYMENT_AMOUNT)
    logger.info("Duplicate detection: file_hash + pHash + file_unique_id + text_hash + check_number")
    logger.info("Supabase: %s", SUPABASE_URL or "NOT CONFIGURED")

    application.run_polling()


if __name__ == "__main__":
    main()
