create table if not exists public.screenshots (
    id            bigint generated by default as identity primary key,
    file_hash     text,
    image_hash    text unique,
    text_hash     text unique,
    check_number  text unique,
    file_unique_id text unique,
    user_id       bigint not null,
    created_at    timestamptz default now()
);

create index if not exists idx_screenshots_hashes
    on public.screenshots (file_hash, image_hash, text_hash, check_number);

-- Enable Row Level Security and add permissive policies
-- so the anon/publishable key can read and insert rows
alter table public.screenshots enable row level security;

create policy "Allow insert" on public.screenshots
    for insert with check (true);

create policy "Allow select" on public.screenshots
    for select using (true);

create policy "Allow update" on public.screenshots
    for update using (true);

create policy "Allow delete" on public.screenshots
    for delete using (true);
