import "@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "@supabase/server";

const createTableSQL = `
create table if not exists public.screenshots (
    id            bigint generated by default as identity primary key,
    file_hash     text,
    image_hash    text unique,
    text_hash     text unique,
    check_number  text unique,
    file_unique_id text unique,
    user_id       bigint not null,
    created_at    timestamptz default now()
);
create index if not exists idx_screenshots_hashes
    on public.screenshots (file_hash, image_hash, text_hash, check_number);
`;

const ENABLE_RLS_SQL = `
alter table public.screenshots enable row level security;
create policy "Allow insert" on public.screenshots for insert with check (true);
create policy "Allow select" on public.screenshots for select using (true);
`;

export default {
  fetch: withSupabase({ auth: ["secret"] }, async (req, ctx) => {
    if (ctx.authMode !== "secret") {
      return new Response("Forbidden — requires secret key", { status: 403 });
    }

    const projectId = process.env.SUPABASE_PROJECT_ID || "efnnlhbcvaymdljjzyec";
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    // Try management API with service_role key
    if (serviceRoleKey) {
      try {
        const resp = await fetch(
          `https://api.supabase.com/v1/projects/${projectId}/sql`,
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${serviceRoleKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              query: createTableSQL + ENABLE_RLS_SQL,
            }),
          }
        );
        if (resp.ok) {
          const result = await resp.json();
          return Response.json({ success: true, result });
        }
        const err = await resp.text();
        console.error("Management API error:", err);
      } catch (e: any) {
        console.error("Management API fetch error:", e.message);
      }
    }

    // Fallback: use supabaseAdmin to verify table exists
    try {
      await ctx.supabaseAdmin
        .from("screenshots")
        .select("id")
        .limit(1)
        .execute();
      return Response.json({ success: true, message: "Table already exists" });
    } catch (e: any) {
      return new Response(
        JSON.stringify({
          success: false,
          message:
            "Service role key required. Or create the table manually in Supabase SQL Editor:",
          sql: createTableSQL + ENABLE_RLS_SQL,
        }),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    }
  }),
};
